### ISSUE TITLE
Hardware test in common

### ISSUE THREAD

**Issue by aransfor** [CampbellGroup/common#116]
There seems to be a test file for Peters dds box in hardware tests. This should probably go in molecules?

**Comment by jayich** [comment]
@aransfor , the corresponding server under test is in common.

**Comment by aransfor** [comment]
I see, perhaps this is not common either

**Comment by jayich** [comment]
Right now the device is specific to molecules, but I don't see that being the case in the future.  I don't think it the server should be moved.

**Comment by aransfor** [comment]
Ok
