### ISSUE TITLE
parameter_vault and the Registry are problematic

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#123]
It appears that unless .pyc files (most likely those associated with parameter vault) are deleted, changes to Registry are reverted when parameter vault is restarted.

**Comment by jayich** [comment]
When shutting down parameter vault from the manager if *.pyc's have not been deleted the original keys and values will get stored in the Registry.

**Comment by jayich** [comment]
In order to make and save changes to parameter vault collections in the registry it appears that parameter vault has to be shutdown, otherwise changes will be reverted when parameter vault is shutdown (regardless of *.pyc files).

**Comment by aransfor** [comment]
@jayich the problem here is that parameter vault does not write dynamically to the registry because the registry is slow, I think the solution is to have parameter vault subscribe to the registry changed signal and update when the registry is manually changed

**Comment by aransfor** [comment]
closing this issue with #212
