### ISSUE TITLE
script_scanner error message

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#14]
When the default parameter value is out of range the error message thrown by script_scanner is not clear, it shows as the parameter is missing.

**Comment by aransfor** [comment]
Im not clear on this, how is the parameter out of range, doesnt the registry fix max/min values and scriptscanner only allow these inputs?

**Comment by aransfor** [comment]
@jayich Just checked this one, It is impossible to put a parameter out of range. What I suspect happened is an invalid parameter was put in the registry and it rightfully said the parameter was missing because it did not get loaded
