### ISSUE TITLE
registry remembers folders changes with shared reactor

### ISSUE THREAD

**Issue by aransfor** [CampbellGroup/common#149]
from now on we should explicitly cd into the whole folder structure e.g.

reg.cd(['', 'settings'])

as apposed to 

reg.cd('settings')

because if a previous event in the reactor has already changed directories you may not be in the top level upon making the connections

**Comment by jayich** [comment]
great point.

**Comment by aransfor** [comment]
fixed with #148

**Comment by jayich** [comment]
Possibly note on the wiki, if we have a registry page.
