### ISSUE TITLE
Need to change datavault file name "dvascii.py" to something more sensible. 

### ISSUE THREAD

**Issue by gregllong** [CampbellGroup/common#16]

**Comment by aransfor** [comment]
I am going to close this issue as we will be merging common with the haeffner lab and dvascii needs to be different than datavault.py as it is different from the martinis group

**Comment by jayich** [comment]
reopening.

**Comment by aransfor** [comment]
@jayich I think we can safely call this datavault.py with the new versioning, is this true?

**Comment by jayich** [comment]
Yes, changing the name should be fine.  I think the module name itself actually doesn't effect the versioning, just what is in the node information.

**Comment by aransfor** [comment]
@jayich bump. I know you understand the versioning and this would go along with #137

**Comment by jayich** [comment]
I think nothing breaks at all if we just change dvascii.py to data_vault.py.  Labrad will still parse through and find the appropriate version of datavault.  I would not bump the data_vault version number for this fix, that is something that could cause problems.

@aransfor , @gregllong , is data_vault.py an okay name?

**Comment by jayich** [comment]
fixed here:  https://github.com/CampbellGroup/common/pull/140
