### ISSUE TITLE
wavemeter client compatibility with WS-8 wavemeter

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#164]
The client will also need to work in a situation where there is no PID control parameter for this particular wavemeter instance.

**Comment by aransfor** [comment]
@jayich I think the config should have a 'isLocking = True' for locking and non locking functions since this actually doesnt depend on the model

**Comment by jayich** [comment]
@aransfor , @theoriginaljuice , we now have a networked functional WS-8 wavemeter.  Please take a look at https://github.com/CampbellGroup/common/tree/164_WS8_wavemeterclient where we have made these changes.  We would like to submit a PR.

**Comment by jayich** [comment]
Move server to a unique directory, ws8_server, or similar.

**Comment by jayich** [comment]
cut copy of "Multiplexserver.py" in the new "Multiplexer directory.

**Comment by jayich** [comment]
@aransfor , it is probably be best to have the wavemeter servers in the same directory, as they are different versions of the same server.  Thoughts?

**Comment by aransfor** [comment]
I think if the plan is to keep the ws8 separate forever it should go in its own folder but if we think it's going to merge later then the same folder makes sense

**Comment by jayich** [comment]
I deleted the duplicate of the PID server code here: https://github.com/CampbellGroup/common/commit/54bbd77260784fd3abf0823396f1314d859df672

The servers should go in the same server (when this gets fixed: https://github.com/CampbellGroup/common/issues/170) they'll be in the same directory.

One should inherit the other, or they should be merged into one server.  Either way, same directory.

**Comment by jayich** [comment]
closed via https://github.com/CampbellGroup/common/pull/171
