### ISSUE TITLE
travis for repo

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#166]
https://travis-ci.org/

**Comment by aransfor** [comment]
@jayich what is this?

**Comment by jayich** [comment]
@aransfor , it builds common on a linux system, and then will run whatever we tell it in the yml file, nominally that will be test code.  It doesn't do much beyond install our requirements at the moment.

**Comment by jayich** [comment]
closed via: https://github.com/CampbellGroup/common/pull/168
