### ISSUE TITLE
pulser_ok complete_infinite_iteration does not work properly

### ISSUE THREAD

**Issue by gregllong** [CampbellGroup/common#180]
If you start a infinite sequence by doing 
'''python
pulser.start_infinite()
'''
stop the infinite sequence by using 
'''python
pulser.complete_infinite_iteration
"""
then you can't start a new pulser sequence. However, if you stop the sequence using
"""python
pulser.stop_sequence()
"""
then you can start a new sequence properly.

**Comment by jayich** [comment]
LGTM

**Comment by aransfor** [comment]
fixed with #181
