### ISSUE TITLE
create new config folder for pulser 2

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#183]
These files are for pulser 1  https://github.com/CampbellGroup/common/tree/master/lib/config/pulser

Not sure of a good way to handle both giving the naming convention.  probably naming one folder pulser_1 and the other pulser_2 is best.

**Comment by aransfor** [comment]
so the config file does not change so It shouldnt matter unless you are running both pulser one and two at the same time which is not possible anyways

**Comment by jayich** [comment]
I think the config classes used for the pulser 1 and pulser 2 are different.  For example

This attribute:  https://github.com/CampbellGroup/qsim_config/blob/master/pulser/hardwareConfiguration.py#L24

does not appear in pulser 1: https://github.com/CampbellGroup/common/blob/master/lib/config/pulser/ddsConfiguration.py

**Comment by aransfor** [comment]
This is fair, frankly I think pulser2 should just be called pulser and the old version should be moved into a deprecated folder so @gregllong can still use it as he is the only one left but is pushing toward the newer pulser. If this is how it will go we should just call the config "pulser" and let @gregllong still grab the old config in his local path. I am open to thoughts however

**Comment by aransfor** [comment]
closing this and opening new issue see #197
