### ISSUE TITLE
protect master

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#186]
We should make master a protected branch that requires at least an approved code review before changes can be merged in.

**Comment by jayich** [comment]
@aransfor thoughts here?  Basically with GitHub settings we can permit code to be merged into master only if it has been reviewed (those with ownership permissions can still merge).  If you give this a thumbs up I'll make the change.

**Comment by aransfor** [comment]
LGTM

**Comment by jayich** [comment]
@aransfor , I enabled the most basic master review protection.  Someone needs to approve the code before it can be merged.  There are finer-grained settings that we could consider but this will likely be good for the foreseeable future.
