### ISSUE TITLE
camera client on remote computer

### ISSUE THREAD

**Issue by fanmingyu212** [CampbellGroup/common#190]
A client (and probably server) that shows images of the camera on computers not directly connected to the camera.

**Comment by aransfor** [comment]
i do not think sending uncompressed video over the network is a good idea @theoriginaljuice and I did a back of the envelope calculation on this and it doesn't look promising...

**Comment by jayich** [comment]
So what does youtube, netflix, etc. do?  The amount of data must be similar, right?  What am I missing here?

It would be great if we could get this to work, but possibly too hard.

**Comment by fanmingyu212** [comment]
I made some changes to the current server and tested it. It seems that with 64 Mbps total bandwidth (upload + download) we can transmit 512 * 512 images at the speed of 2 frames per second. I am not sure if it would be enough though. There are possibly some ways we can compress the images to improve the speed. I think compressing videos like what youtube and netflix do needs huge amount of calculation power and we probably could not do that.

**Comment by aransfor** [comment]
the compress data then buffer, 2 frames per second is pretty slow, we operate at 10-100Hz i think the image data is 32bits per pixel and there are about 1 million pixels so at 10 Hz you need 320 Mbs uncompressed and unbuffered, seems unlikely to be worth the effort compared to just buying a second monitor and a $20 cable

**Comment by theoriginaljuice** [comment]
I agree with Ransford on this. I think it would be awesome if it were easy, but it seems like way too much work for the reward.
