### ISSUE TITLE
in arduinoTTL server function ttl_read(chan) changes output

### ISSUE THREAD

**Issue by annaliw** [CampbellGroup/common#193]
When I use the function ttl_read(chan) it rewrites the TTL output to False instead of just returning the TTL state. Has anyone else seen this?

**Comment by theoriginaljuice** [comment]
Ya it doesn't work right. On a long list of things to fix. If you could figure it out and submit a fixed pull request that would be awesome!!

**Comment by aransfor** [comment]
It supposed to do that, you cant read an out put your writing to. When you change an Arduino to "readmode" on a pin it can no longer define an output and goes into high impedence mode. The read is designed to read external TTLs not tell you what TTL you output

**Comment by annaliw** [comment]
Okay, thanks for explaining that. The function's other name (TTLInput) makes more sense to me now.
