### ISSUE TITLE
move dac8718 to common

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#195]
@aransfor , we are interested in using this server: https://github.com/CampbellGroup/Qsim/tree/master/servers/dac8718server  

can we put this in common?

**Comment by aransfor** [comment]
@jayich of course

**Comment by aransfor** [comment]
actually @theoriginaljuice is about to use this dac as well so it will be perfect on common

**Comment by jayich** [comment]
Okay, should we go ahead and submit a PR?  basically just copying and pasting to common from Qsim.

**Comment by aransfor** [comment]
ya submit a PR so people see it but ill just LGTM it




*Anthony Ransford*
Graduate Student
UCLA Physics and Astronomy
Lab: PAB B-707
Phone: (310) 206-6982 | Email: ransfordanthony@gmail.com
http://campbellgroup.physics.ucla.edu/home

**Comment by jayich** [comment]
closed via: https://github.com/CampbellGroup/common/pull/196
