### ISSUE TITLE
iXonServer save picture format

### ISSUE THREAD

**Issue by fanmingyu212** [CampbellGroup/common#198]
The picture saving format is ambiguous. For example, a picture taken at 2017-09-07 09:03:24:091 is saved as "201797932491.csv", which may cause confusion on the date and time. The file format is also not CSV too.

**Comment by fanmingyu212** [comment]
@aransfor Do you think changing the data format to csv is a good idea? Also there are many trailing zeros in the saved data because the program saves too many digits. Maybe the saved digits can be reduced to minimize file size.

**Comment by aransfor** [comment]
I'm not sure what you guys are referring to, we save pictures in two ways, 1. Right click and save 2. Through the server us get image which returns a numpy array. Both of these methods allow saving of files however you please

**Comment by fanmingyu212** [comment]
Do you use the checkbox "Save Images" in the iXonServer GUI interface? The code associated is https://github.com/CampbellGroup/common/blob/master/lib/servers/iXonServer/AndorVideo.py#L212. We are using this checkbox to save images.
