### ISSUE TITLE
scriptscanner should order parameters alphabetically

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#20]

**Comment by aransfor** [comment]
I would think this will be easy...

**Comment by aransfor** [comment]
@jayich unless Im missing something, my parameters are all alphabetical, also the categories are alphabetical

**Comment by aransfor** [comment]
@jayich bump

**Comment by jayich** [comment]
Is there an issue if some parameters are capitalized?

If it sorts by capitals I'm not interested in fixing, we'll just lowercase everything.

**Comment by aransfor** [comment]
It is case insensitive and alphebatized for collections and parameters inside collection I have just checked closing..

**Comment by jayich** [comment]
@aransfor , excellent.
