### ISSUE TITLE
Server for the MOTion control unit

### ISSUE THREAD

**Issue by fanmingyu212** [CampbellGroup/common#206]
@theoriginaljuice Do you have a server for the MOTion control unit? I can write a server for the control box if it does not exist.

**Comment by theoriginaljuice** [comment]
Yes I do. You're referring to the rf electronics I assume? In the
barium-project repo on Github it's called TrapServer.

Justin

**Comment by fanmingyu212** [comment]
@theoriginaljuice Could you upload the server to common if possible? We would like to use the server to control our rf electronics box.

**Comment by fanmingyu212** [comment]
@theoriginaljuice I can also add it to common if you can give me the access to the barium-project repo. Thank you.

**Comment by theoriginaljuice** [comment]
You should be able to clone the barium-project without any special
permissions. We typically do not add things to common though unless it is
something that everyone uses. In this case I'm not sure this server belongs
in common, but rather in your experiment folder.

**Comment by fanmingyu212** [comment]
@theoriginaljuice Thank you very much for the information. I will not add it to common then.

**Comment by theoriginaljuice** [comment]
No problem, and don't forget to clone the config folder as well and modify
the trap server config file accordingly.

Justin
