### ISSUE TITLE
data vault dying

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#21]
A memory error causes data vault to fail after too many matrices have been saved.

**Comment by aransfor** [comment]
In what way does it fail? is there an error message?

**Comment by aransfor** [comment]
is this  still an issue? and if so we need more info like what is the error message, how/when does it fail

**Comment by jayich** [comment]
This happened again tonight.  We have saved a screenshot of the error message.

**Comment by aransfor** [comment]
@gregllong are you still using datavault for images? We have been using datavault for years now and it hasnt crashed once so I assume this is an image issue

**Comment by gregllong** [comment]
I am and I think it is an image issue. We are thinking about moving the image format to hdf5, but that is yet to be implemented.

**Comment by aransfor** [comment]
fixed by #160
