### ISSUE TITLE
client manager

### ISSUE THREAD

**Issue by fanmingyu212** [CampbellGroup/common#216]
A client manager to start/stop the clients from gui, similarly to how the labrad manager starts the servers. Then we do not need to open cmd window when starting clients.

It can list all .py files from clients folders. For every client, there could be four buttons to start, stop, add to quick access, and ignore. "Add to quick access" and "Ignore" will filter the clients shown on the gui, similarly to how autostart in labrad manager works. 

Possibly the client manager can record the process id when it starts a client, so it can terminate the client when we click "stop".

**Comment by aransfor** [comment]
This is probably not something that belongs on common. We all have guis that run our clients in experiment specific repos

**Comment by fanmingyu212** [comment]
I thought it might be useful for the guis that run separate experiment. It can be added to the gui (command center) and then non mission critical but often used clients (power meter client, for example) can be run from the client manager. However, if you think it would not be very helpful for you, I will close the issue.
