### ISSUE TITLE
data vault saving values with arbitrary headers in .ini files

### ISSUE THREAD

**Issue by fanmingyu212** [CampbellGroup/common#238]
Data vault can only save `Independent`, `Dependent`, `Parameter`, and `Comment` in the .ini file now. A function that saves a value under an arbitrary header name could be helpful to save measured values such as temperature, and wavemeter wavelength. 

It will also enable general naming schemes to organize the values in the .ini files.

@aransfor could you take a look at this issue and let me know what you think before I start working on this issue?

**Comment by aransfor** [comment]
@fanmingyu212 can you not save an arbitrary heading for a parameter? such as parameter = (temperature, 20 deg) or paramter= (wavelength, 369nm). This is how we do this.

**Comment by fanmingyu212** [comment]
@aransfor we would like to use a more flexible way to save data. Currently we can only save four types of headers,  `Independent`, `Dependent`, `Parameter`, and `Comment`. We would like to save data in the .ini file depends on the use case, and also to save measurements that are not paramaters in the .ini file.

**Comment by fanmingyu212** [comment]
If you have steps on how to reproduce this bug it would be great.

**Comment by jayich** [comment]
@fanmingyu212 is this issue addressed?

**Comment by fanmingyu212** [comment]
@jayich Yes. It is addressed.
