### ISSUE TITLE
ScriptScanner save parameters

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#32]
It would be great to have a button on ScriptScanner that saves all of the current parameters values to ParameterVault.

**Comment by aransfor** [comment]
just checked this all parameters are saved every time a parameter is changed.

**Comment by jayich** [comment]
@aransfor , just to be clear, you don't need to run an experiment for the parameters to be saved?

**Comment by aransfor** [comment]
@jayich nope, just checked it
