### ISSUE TITLE
scriptscanner - can't enter values easily

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#35]
You can't type values into the parameter spinbox outside of the allowed parameter range.

For example if 0 is not an allowed value I can't delete 1 and then type 2 because 0 is not an allowed value.

**Comment by jayich** [comment]
also can't type in more than the allowed precision, so if there are too many zeroes for example you have to delete them.

**Comment by aransfor** [comment]
@jayich I looked into this a bit. It seems this is a limitation of how the qspinbox works fundamentally, not scriptscanner. I will look a little bit more but this may not be possible without creating a custom widget in a non-trivial way

**Comment by aransfor** [comment]
this is a pyqt "bug"
