### ISSUE TITLE
No autoplot when scanning with scriptscanner

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#52]
A pygrapher live window automatically appears when you scan a variable over multiple experiments.

**Comment by aransfor** [comment]
Im not sure what to say about this except that moving to the new grapher seems like a good idea since the pygrapherlive code is a shit show

**Comment by jayich** [comment]
This problem is grapher independent.

**Comment by aransfor** [comment]
maybe I misunderstand, the new grapher doesnt even use matplotlib... I believe this is a problem with data vault taking the plotlive=True function many times which again doesnt exist in the new grapher, it takes the ouptut of a dataset and plots on a single tab. No windows pop up ever on the new grapher

**Comment by jayich** [comment]
Sounds good.

**Comment by aransfor** [comment]
fixed with new grapher
