### ISSUE TITLE
wavemeter client does not look at current wavemeter settings

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#56]
I believe the default functionality for things such as exposure time for a wavemeter client should be to check the exposure time setting on the wavemeter and use that value.  I don't think this is the case at present.

**Comment by aransfor** [comment]
to clarify, when starting a client the exposure can be changed from the last set value. Im assigning this as a bug to @theoriginaljuice since he is ass deep in wavemeter stuff right now

**Comment by aransfor** [comment]
we tracked this down to a bug with the wavemeter firmware, it sends the wrong current exposure on startup
