### ISSUE TITLE
data vault signal when CSV is done being written

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#6]
Need this for reliable automated analysis

@aransfor

**Comment by aransfor** [comment]
I am assigning this to XP so he can see if this is still required as I believe this is sorted out. XP close this if it is no longer an issue

**Comment by aransfor** [comment]
def addData(self, data):
        varcount = len(self.independents) + len(self.dependents)
        if not len(data) or not isinstance(data[0], list):
            data = [data]
        if len(data[0]) != varcount:
            raise BadDataError(varcount, len(data[0]))

        # append the data to the file
        self._saveData(data)

        # notify all listening contexts
        self.parent.onDataAvailable(None, self.listeners)


this is the code the signal is onDataAvailable

it is used in RSG for example
