### ISSUE TITLE
script scanner node startup

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#7]
Script scanner does not reliable start when running the node script.

**Comment by aransfor** [comment]
low priority bug will look at though

**Comment by jayich** [comment]
hitting this bug again.

**Comment by aransfor** [comment]
have you looked at the node script on this to debug it?

**Comment by aransfor** [comment]
I have figured out what is going on and opened up a more explicit issue here

https://github.com/CampbellGroup/common/issues/71
