### ISSUE TITLE
qt4reactor should go in site-packages

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#76]
See the module page here:

https://pypi.python.org/pypi/qt4reactor/1.6

We should remove this code from common.

**Comment by aransfor** [comment]
So we should make qt4reactor its own folder in site-packages? i don't quite understand that link, how do people who use this deal with this?

**Comment by jayich** [comment]
We should just trying running pip install qt4reactor and see if/where it is installed.

**Comment by aransfor** [comment]
sounds good, ill look into it tomorrow perhaps

**Comment by jayich** [comment]
This appears to be the GitHub site for qt4reactor.py

https://github.com/ghtdak/qtreactor

Perhaps though we should get it from pypi.

**Comment by aransfor** [comment]
closing issue due to #101
