### ISSUE TITLE
Distribute a hook that prevents pushing to master.

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#78]

**Comment by aransfor** [comment]
what is this hook?

**Comment by jayich** [comment]
I think we want a pre-push hook that just blocks any pushes to origin/master.

overview:
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by aransfor** [comment]
pre-push hooks would require a file on every computer and window/linux nonsense. GIThub now provides protected branches and I have protected master from force pushes and deletion
