### ISSUE TITLE
Wavemeter legacy code

### ISSUE THREAD

**Issue by aransfor** [CampbellGroup/common#83]
@gregllong @jayich Since the wavemeter clients, widgets and experiments, locking and line scans (as well as Hudson experiments) and such use the old style method naming (ie changeExposure) for methods this should be refactored some time in the future. As for the new modifications I propose we stay consistent here with the old style as @theoriginaljuice  has done.

pep8 says,

Function Names
Function names should be lowercase, with words separated by underscores as necessary to improve readability.

**mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.**

also,

New modules and packages (including third party frameworks) should be written to these standards, **but where an existing library has a different style, internal consistency is preferred.**

**Comment by jayich** [comment]
I propose we break from camel case with all new functionality, and use lower case with underscores for functions and methods and capitalize words in class names.

**Comment by aransfor** [comment]
What is camel case? I assume you mean the mixedcase? I agree. That's why I started this refactoring issue. I'm just not sure anyone has the time to do it right now

**Comment by jayich** [comment]
I'm proposing that we don't use camel case for all new functionality, so new edits that @theoriginaljuice  is making fall under this umbrella.  Refactoring sounds great.

**Comment by aransfor** [comment]
I guess this would be explicitly not pep8

**Comment by jayich** [comment]
pep8 changes made here: https://github.com/CampbellGroup/common/pull/84

**Comment by aransfor** [comment]
Fixed in #84
